name: PR build

on:
    workflow_dispatch:
    pull_request:
        branches: [main]

env:
  NAMESPACE: jaydee029

jobs:
    build-gradle:
        name: build and Test Gradle 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup JDK 
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'semeru'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                gradle-version: 6.9.2

            - name: Test and Build Gradle
              run: |
               gradle clean build \
               -PsourceMaven=https://repo.maven.apache.org/maven2/  \
               -PcentralMaven=https://repo.maven.apache.org/maven2/ \
               -PtargetMaven=https://maven.pkg.github.com/${{env.NAMESPACE}}/gradle/
          